services:
  ollama:
    container_name: imasu_ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - imasu_network

  api:
    container_name: imasu-api-1
    image: imasu-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - imasu_network
    volumes:
      - ./output:/app/output
    # MAKE SURE THIS SECTION EXISTS AND IS CORRECT #
    environment:
      - OLLAMA_URL=http://ollama:11434
      - A1111_URL=http://host.docker.internal:7860
    depends_on:
      - ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - imasu_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  imasu_network:
    driver: bridge

volumes:
  ollama_data:
