version: "3.9"

services:
  ollama:
    image: ollama/ollama:0.11.11
    container_name: imasu_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - imasu_network

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    depends_on:
      - ollama
    networks:
      - imasu_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  ui:
    build:
      context: .
      dockerfile: ./Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - imasu_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  imasu_network:
    driver: bridge

volumes:
  ollama_data:
