services:
  ollama:
    image: ollama/ollama:0.11.11
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: imasu_ollama
    networks:
      - imasu_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    depends_on:
      - ollama
    networks:
      - imasu_network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - imasu_network

networks:
  imasu_network:
    driver: bridge

volumes:
  ollama_data:
